# Generated by Django 4.0.3 on 2022-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_projects_entrepreneurdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='organization',
            new_name='organization_name',
        ),
        migrations.AlterField(
            model_name='projects',
            name='document1',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='document2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
