# Generated by Django 4.0.3 on 2022-03-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_projects_document1_alter_projects_document2'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=12)),
                ('landline_number', models.CharField(max_length=12)),
                ('website', models.URLField(blank=True, default='')),
                ('state', models.CharField(choices=[('Andaman and Nicobar', 'Andaman and Nicobar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('about', models.TextField()),
                ('focus_industries', multiselectfield.db.fields.MultiSelectField(choices=[('ARTIFICIAL INTELLIGENCE', 'ARTIFICIAL INTELLIGENCE'), ('SMART AUTOMATION', 'SMART AUTOMATION'), ('FITNESS & SPORTS', 'FITNESS & SPORTS'), ('HERITAGE & CULTURE', 'HERITAGE & CULTURE'), ('MEDTECH/BIOTECH/ HEALTHTECH', 'MEDTECH/BIOTECH/ HEALTHTECH'), ('SMART VEHICLES', 'SMART VEHICLES'), ('FINANCE', 'FINANCE'), ('ARICULTURE, FOODTECH & RURAL DEVELOPMENT', 'ARICULTURE, FOODTECH & RURAL DEVELOPMENT'), ('ROBOTICS AND DRONES', 'ROBOTICS AND DRONES'), ('TRANSPORTATION', 'TRANSPORTATION'), ('TOURISM', 'TOURISM'), ('CLEAN & GREEN TECHNOLOGY', 'CLEAN & GREEN TECHNOLOGY'), ('BLOCKCHAIN & CYBERSECURITY', 'BLOCKCHAIN & CYBERSECURITY'), ('RENEWABLE/ SUSTAINABLE ENERGY', 'ENEWABLE/ SUSTAINABLE ENERGY'), ('SMART EDUCATION', 'SMART EDUCATION'), ('DISASTER MANAGEMENT', 'DISASTER MANAGEMENT'), ('AERONAUTICS', 'AERONAUTICS'), ('MISCELLANEOUS', 'MISCELLANEOUS')], max_length=355)),
                ('focus_sectors', multiselectfield.db.fields.MultiSelectField(choices=[('Big Data', 'Big Data'), ('Business Intelligence', 'Business Intelligence'), ('Machine Learning', 'Machine Learning'), ('NLP', 'NLP'), ('Bitcoin and Blockchain', 'Bitcoin and Blockchain'), ('Pharmaceutical', 'Pharmaceutical'), ('Digital Media Publishing', 'Digital Media Publishing'), ('Foreign Exchange', 'Foreign Exchange'), ('Food Processing', 'Food Processing'), ('Healthcare Services', 'Healthcare Services'), ('Virtual Games', 'Virtual Games'), ('Trading', 'Trading'), ('Augmented + Virtual Reality', 'Augmented + Virtual Reality'), ('Construction Technologies', 'Construction Technologies'), ('Smart Home', 'Smart Home'), ('Internet of Things', 'Internet of Things'), ('Crowdfunding', 'Crowdfunding'), ('P2P', 'P2P'), ('Finance', 'Finance'), ('E-commerce', 'E-commerce'), ('SAAS', 'SAAS'), ('Others', 'Others')], max_length=321)),
                ('startup_stages', multiselectfield.db.fields.MultiSelectField(choices=[('Ideation', 'Ideation'), ('Validation', 'Validation'), ('EarlyTraction', 'EarlyTraction'), ('Scaling', 'Scaling')], max_length=41)),
                ('min_investment_range', models.IntegerField()),
                ('max_investment_range', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'InvestorDetails',
            },
        ),
    ]
