# Generated by Django 4.0.3 on 2022-03-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_investordetails_landline_number_mentordetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrepreneurdetails',
            options={'verbose_name_plural': 'EntrepreneurDetails'},
        ),
    ]
