# Generated by Django 4.0.3 on 2022-03-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('modules', models.IntegerField()),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
