# Generated by Django 4.0.3 on 2022-03-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'StartUps',
            },
        ),
    ]
