# Generated by Django 4.0.3 on 2022-03-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_startups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('scheme_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=254)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Schemes',
            },
        ),
    ]
